---
- name: Allow Developer Access To Dev Servers
  hosts: dev_web_servers
  gather_facts: no
  tasks:
    - name: Create shared account
      user:
        name: developer
        state: present
     
    - name: Set up multiple authorized keys
      authorized_key:
        user: developer
        state: present
        key: "{{ item }}"
      loop: "{{ public_key_lists | map(attribute='public_keys') | flatten }}"
