---
- hosts: server1.example.com
  gather_facts: no
  tasks:
    - name: creating users
      vars:
        password: "{{ lookup('password', 'credentials/' + item + ' length=9') }}"
      user:
        name: "{{ item }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
      loop: "{{ query('lines', 'cat users.txt') }}"
