---
- name: creating users from list file
  hosts: 192.168.56.103
  vars:
    password: "{{ lookup('password', 'credentials/' + item + ' length=9') }}"
  tasks:
    - name: create users
      user:
        name: "{{ item }}"
        password: "{{ password | password_hash('sha512') }}"
      loop: "{{ query('lines', 'cat users.txt') }}"
