---
# handlers file for roles/haproxy
- name: restart haproxy
  service:
    name: haproxy
    state: restarted
  become: true

- name: reload haproxy
  service:
    name: haproxy
    state: reloaded
  become: true
